import '@fontsource/inter/400.css'
import '@fontsource/inter/500.css'
import '@fontsource/inter/600.css'
import '@fontsource/inter/700.css'

import '../css/tokens.css'
import '../css/base.css'
import '../css/components/buttons.css'
import '../css/components/header.css'
import '../css/components/hero.css'
import '../css/components/services-grid.css'
import '../css/components/how-we-work.css'
import '../css/components/case-teaser.css'
import '../css/components/footer.css'
