import '@fontsource/sora/300.css'
import '@fontsource/sora/400.css'
import '@fontsource/sora/600.css'
import '@fontsource/sora/700.css'
import '@fontsource/inter/400.css'
import '@fontsource/inter/500.css'
import '@fontsource/inter/600.css'
import '@fontsource/inter/700.css'

import '../css/tokens.css'
import '../css/base.css'
import '../css/components/buttons.css'
import '../css/components/header.css'
import '../css/components/hero.css'
import '../css/components/services-grid.css'
import '../css/components/how-we-work.css'
import '../css/components/case-teaser.css'
import '../css/components/footer.css'
import '../css/components/about.css'
import '../css/components/service-page.css'
import '../css/components/portfolio.css'
import '../css/components/contact-form.css'
import '../css/components/whatsapp-btn.css'
import '../css/components/blog-list.css'

import './scroll.js'
